name: Build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Save last tag
        run: curl --silent 'https://api.github.com/repos/dreamhead/moco/tags?per_page=1' | grep name | sed -E 's/.*"([^"]+)".*/\1/' > tag
      -
        name: Commit file
        uses: test-room-7/action-update-file@v1
        with:
          file-path: tag
          commit-msg: Update tag
          github-token: ${{ secrets.GH_TOKEN }}
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to ECR
#        uses: docker/login-action@v1
#        with:
#          registry: public.ecr.aws
#          username: ${{ secrets.AWS_KEY }}
#          password: ${{ secrets.AWS_SECRET }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: false
#          tags: public.ecr.aws/e1p2r1f0/moco:latest
