name: Build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Save last tag
        run: ./check_update.sh
      -
        name: Login to ECR
        if: env.EXIT == 'false'
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_KEY }}
          password: ${{ secrets.AWS_SECRET }}
      -
        name: Set up QEMU
        if: env.EXIT == 'false'
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: env.EXIT == 'false'
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        if: env.EXIT == 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: public.ecr.aws/e1p2r1f0/moco:latest
      -
        name: Commit file
        if: env.EXIT == 'false'
        uses: test-room-7/action-update-file@v1
        with:
          file-path: tag
          commit-msg: Update tag
          github-token: ${{ secrets.GH_TOKEN }}
